add_newline = false
format = "$time$directory$container$git_branch\n$character\n"

[character]
error_symbol = "[• 󰅙](bold fg:red) "
success_symbol = "[• ](bold fg:blue) "

[directory]
format = "[](bold fg:blue)[$path ]($style)[](bold fg:blue)"
home_symbol = "  "
read_only = "  "
style = "bg:blue fg:black"
truncation_length = 6
truncation_symbol = "••/"

[directory.substitutions]
Desktop = "  "
Documents = "  "
Downloads = "  "
Music = " 󰎈 "
Pictures = "  "
Videos = "  "

[git_branch]
format = " • [](bold fg:green)[$symbol $branch(:$remote_branch)](fg:black bg:green)[ ](bold fg:green)"
style = "bg: green"
symbol = "󰘬"
truncation_length = 4
truncation_symbol = ""

[hostname]
disabled = false
format = "[•$hostname](bg:cyan bold fg:black)[](bold fg:cyan )"
ssh_only = false
trim_at = ".cs.wisc.edu"

[line_break]
disabled = false

[container]
disabled = false
format = " • [](bold fg:blue)[ $symbol]($style)[](bold fg:blue)"
style = "bg:blue fg:black"
symbol = "󰏖 "

[time]
disabled = false
format = "[](bold fg:yellow)[ $time](bold bg:yellow fg:black)[](bold fg:yellow) •• "
time_format = "%R"

[username]
disabled = false
format = "[](bold fg:cyan)[$user]($style)[](bold fg:cyan)"
show_always = true
style_root = "red bold"
style_user = "bold bg:cyan fg:black"
