# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

status is-login; and begin

    # Login shell initialisation
    set -g -x PATH $PATH /home/mjs/.local/bin/
    set -g -x EDITOR /home/mjs/.local/bin/nvim
    set -g -x GTK_THEME catppuccin-mocha-pink-standard+default
    eval (ssh-agent -c)
end

status is-interactive; and begin

    # Abbreviations


    # Aliases
    alias cs400-auth 'gcloud auth login'
    alias cs400-ssh 'gcloud compute ssh --zone "us-central1-a" "cs400-vm" --project "cs-400-398116"'
    alias dup-files 'find . -type f -printf '\''%p -> %f\n'\'' | sort -k2 | uniq -f1 --all-repeated=separate'
    alias flatten 'find */ -type f -exec sh -c '\''file=${1#./}; mv "$file" "$(basename $file)"'\'' _ '\''{}'\'' \; ; find */ -depth -type d -exec rmdir '\''{}'\'' \;'
    alias icat swayimg
    alias ls eza
    alias m math
    alias mjs-bulk-rename 'find . -depth -exec fish -c '\''mjs-rename "{}"'\'' \;'
    alias nix-shell 'nix-shell --run fish'
    alias vi nvim

    # Interactive shell initialisation
    if test "$TERM" != dumb
        eval (starship init fish)

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION "no-rc no-cursor"
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/mjs/.local/share/fish/home-manager_generated_completions" $post
    end

end
