require "mjs.impatient" -- First to captialize performance gains
require "mjs.options"
require "mjs.keymaps"
require "mjs.plugins"
require "mjs.colorscheme"
require "mjs.cmp"
require "mjs.lsp"
require "mjs.telescope"
require "mjs.treesitter"
require "mjs.autopair"
require "mjs.comment"
require "mjs.nvim-tree"
require "mjs.lualine"
require "mjs.alpha"
